=== isonovio/ninjas-archive/src/lib/data/schemas/event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "participants", "matches"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "../schemas/slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "../schemas/daterange.schema.json" },
        "urls": { "type": "object", "propertyNames": { "type": "string" }, "additionalProperties": { "type": "string", "format": "uri" } },
        "participants": { "type": "object", "propertyNames": { "$ref": "../schemas/slug.schema.json" }, "additionalProperties": { "$ref": "../schemas/slug.schema.json" } },
        "matches": { "type": "array", "items": { "$ref": "#/$defs/match" } },
        "note": { "type": "string" }
    },

    "$defs": {
        "match": {
            "type": "object",
            "required": ["slug", "bracket", "date", "matchup", "maps"],
            "additionalProperties": false,
            "properties": {
                "slug": { "$ref": "../schemas/slug.schema.json" },
                "bracket": { "type": "array", "items": { "type": "string" } },
                "date": { "type": "string", "format": "date" },
                "matchup": { "$ref": "#/$defs/matchup" },
                "url": { "type": "string", "format": "uri" },
                "maps": { "type": "array", "items": { "$ref": "#/$defs/map" } },
                "note": { "type": "string" }
            }
        },

        "matchup": {
            "type": "object",
            "required": ["team1", "team2"],
            "additionalProperties": false,
            "properties": {
                "team1": { "type": "string" },
                "team2": { "type": "string" }
            }
        },

        "map": {
            "type": "object",
            "required": ["slug", "map", "result"],
            "additionalProperties": false,
            "properties": {
                "slug": { "type": "string", "pattern": "^map[1-5]$" },
                "map": { "$ref": "../schemas/cs-map.schema.json" },
                "result": { "type": "string", "pattern": "^[0-9]+:[0-9]+$" },
                "url": { "type": "string", "format": "uri" },
                "streams": { "type": "array", "items": { "$ref": "#/$defs/stream" } },
                "note": { "type": "string" }
            }
        },

        "stream": {
            "type": "object",
            "required": ["url", "caster", "language"],
            "additionalProperties": false,
            "properties": {
                "url": { "type": "string", "format": "uri" },
                "caster": { "type": "string" },
                "language": { "$ref": "../schemas/language.schema.json" },
                "duration": { "$ref": "../schemas/timerange.schema.json" },
                "tags": { "type": "array", "items": { "$ref": "#/$defs/stream-tag" } }
            }
        },
        "stream-tag": {
            "type": "string",
            "enum": ["official", "incomplete", "part1", "part2"]
        }
    }
}

=== isonovio/ninjas-archive/src/lib/data/events/2026-02-09-jbpl-2026-fe-1-g.json
{
    "$schema": "../schemas/event.schema.json",

    "slug": "jbpl-2026-fe-1-g",
    "name": "JB Pro League 2026 Female #1 Group Stage",
    "duration": { "start": "2026-02-09", "end": "2026-02-01" },
    "urls": {
        "Officail Website": "https://jbproleague.com/news/11b110d1-1125-483a-b5bd-bcbd115afac4",
        "Rules": "https://github.com/VANTAGL/JB-Pro-League-2026-female-1",
        "HLTV": "https://www.hltv.org/events/8929/jb-pro-league-female-season-1"
    },
    "participants": { "big": "big-equipa-2026-1", "pkb": "peekaboo-2026-1", "lhc": "let-her-cook-2026-1" },
    "matches": [
        {
            "slug": "match02",
            "bracket": ["Group A", "Opening round", "Match 2"],
            "date": "2026-02-09",
            "matchup": { "team1": "pkb", "team2": "Fingers Crossed Fe" },
            "url": "https://www.hltv.org/matches/2390089/peekaboo-vs-fingers-crossed-fe-jb-pro-league-female-season-1",
            "maps": [
                { "slug": "map1", "map": "d2", "result": "13:9", "streams": [{ "caster": "LucyLuce", "language": "en", "tags": ["official"], "parts": [{ "name": "VOD", "url": "https://www.twitch.tv/videos/2693315503", "duration": "03:49:25-04:33:26" }] }] },
                { "slug": "map2", "map": "anc", "result": "13:11", "streams": [{ "caster": "LucyLuce", "language": "en", "tags": ["official"], "parts": [{ "name": "VOD", "url": "https://www.twitch.tv/videos/2693315503", "duration": "04:41:17-05:28:33" }] }] }
            ],
            "note": "Angelka stood in for Zana on map1."
        },
        {
            "slug": "match03",
            "bracket": ["Group B", "Opening round", "Match 1"],
            "date": "2026-02-10",
            "matchup": { "team1": "big", "team2": "confidence" },
            "url": "https://www.hltv.org/matches/2390090/big-equipa-vs-confidence-jb-pro-league-female-season-1",
            "maps": [
                {
                    "slug": "map1",
                    "map": "anb",
                    "result": "19:17",
                    "streams": [
                        {
                            "caster": "Affinity",
                            "language": "en",
                            "tags": ["official"],
                            "parts": [
                                { "name": "Part 1", "url": "https://www.twitch.tv/videos/2694143260", "duration": "00:32:33-00:49:20" },
                                { "name": "Part 2", "url": "https://www.twitch.tv/videos/2694180474", "duration": "00:00:00-01:09:45" }
                            ]
                        }
                    ]
                },
                { "slug": "map2", "map": "anc", "result": "13:6", "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "name": "VOD", "url": "https://www.twitch.tv/videos/2694180474", "duration": "01:20:55-02:05:43" }] }] }
            ]
        },
        {
            "slug": "match04",
            "bracket": ["Group B", "Opening round", "Match 2"],
            "date": "2026-02-10",
            "matchup": { "team1": "lhc", "team2": "hindsight" },
            "url": "https://www.hltv.org/matches/2390091/let-her-cook-vs-hindsight-jb-pro-league-female-season-1",
            "maps": [
                { "slug": "map1", "map": "mrg", "result": "13:9", "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "name": "VOD", "url": "https://www.twitch.tv/videos/2694180474", "duration": "02:58:59-03:51:14" }] }] },
                { "slug": "map2", "map": "anc", "result": "16:19", "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "name": "VOD", "url": "https://www.twitch.tv/videos/2694180474", "duration": "04:01:27-05:11:19" }] }] },
                { "slug": "map2", "map": "anb", "result": "13:4", "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "name": "VOD", "url": "https://www.twitch.tv/videos/2694180474", "duration": "05:21:05-05:56:49" }] }] }
            ]
        },
        {
            "slug": "match05",
            "bracket": ["Group A", "Winner's match"],
            "date": "2026-02-11",
            "matchup": { "team1": "Pigeons", "team2": "pkb" },
            "url": "https://www.hltv.org/matches/2390092/pigeons-vs-peekaboo-jb-pro-league-female-season-1",
            "maps": []
        },
        {
            "slug": "match06",
            "bracket": ["Group B", "Winner's match"],
            "date": "2026-02-11",
            "matchup": { "team1": "big", "team2": "lhc" },
            "url": "https://www.hltv.org/matches/2390093/big-equipa-vs-let-her-cook-jb-pro-league-female-season-1",
            "maps": []
        }
    ]
}

=== isonovio/ninjas-archive/src/lib/data/events/2026-01-24-jbpl-2026-fe-1-q2.json
{
    "$schema": "../schemas/event.schema.json",

    "slug": "jbpl-2026-fe-1-q2",
    "name": "JB Pro League 2026 Female #1 Qualifier 2",
    "duration": { "start": "2026-01-24", "end": "2026-01-25" },
    "urls": {
        "Officail Website": "https://jbproleague.com/news/11b110d1-1125-483a-b5bd-bcbd115afac4",
        "Bracket": "https://www.challengermode.com/s/JBProLeague/tournaments/af8accf4-262d-44fb-1876-08de40692357"
    },
    "participants": { "pkb": "peekaboo-2026-1", "lhc": "let-her-cook-2026-2" },
    "matches": [
        {
            "slug": "s1q2m17",
            "bracket": ["Round of 16", "Match 1"],
            "date": "2026-01-24",
            "matchup": { "team1": "lhc", "team2": "FUTURE W" },
            "maps": [
                { "slug": "map1", "map": "d2", "result": "13:3", "url": "https://www.challengermode.com/s/JBProLeague/games/b24dec54-ce34-4b17-d815-08de5760407c" },
                { "slug": "map2", "map": "anc", "result": "13:7", "url": "https://www.challengermode.com/s/JBProLeague/games/f886aeb0-3e71-45cd-d87f-08de5760407c" }
            ]
        },
        {
            "slug": "s1q2m23",
            "bracket": ["Round of 16", "Match 7"],
            "date": "2026-01-24",
            "matchup": { "team1": "pkb", "team2": "confidence" },
            "maps": [
                { "slug": "map1", "map": "anc", "result": "13:2", "url": "https://www.challengermode.com/s/JBProLeague/games/a1e1b576-71d9-4682-d87b-08de5760407c" },
                { "slug": "map2", "map": "mrg", "result": "17:19", "url": "https://www.challengermode.com/s/JBProLeague/games/a9c5bf63-7395-4ac7-d8de-08de5760407c" },
                { "slug": "map3", "map": "d2", "result": "13:10", "url": "https://www.challengermode.com/s/JBProLeague/games/ac782289-ad13-4385-d9f9-08de5760407c" }
            ]
        },
        {
            "slug": "s1q2m25",
            "bracket": ["Quarter finals", "Match 1"],
            "date": "2026-01-25",
            "matchup": { "team1": "lhc", "team2": "imodium" },
            "maps": [
                { "slug": "map1", "map": "", "result": "", "url": "" },
                { "slug": "map2", "map": "", "result": "", "url": "" },
                { "slug": "map3", "map": "", "result": "", "url": "" }
            ]
        },
        {
            "slug": "s1q2m28",
            "bracket": ["Quarter finals", "Match 4"],
            "date": "2026-01-25",
            "matchup": { "team1": "pkb", "team2": "chicken friday" },
            "maps": [
                { "slug": "map1", "map": "", "result": "", "url": "" },
                { "slug": "map2", "map": "", "result": "", "url": "" },
                { "slug": "map3", "map": "", "result": "", "url": "" }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/src/lib/data/events/2026-01-31-jbpl-2026-fe-1-q3.json
{
    "$schema": "../schemas/event.schema.json",

    "slug": "jbpl-2026-fe-1-q3",
    "name": "JB Pro League 2026 Female #1 Qualifier 3",
    "duration": { "start": "2026-01-31", "end": "2026-02-01" },
    "urls": {
        "Officail Website": "https://jbproleague.com/news/11b110d1-1125-483a-b5bd-bcbd115afac4",
        "Bracket": "https://www.challengermode.com/s/JBProLeague/tournaments/acd3cf54-edac-4040-1877-08de40692357"
    },
    "participants": { "lhc": "let-her-cook-2026-2" },
    "matches": [
        {
            "slug": "match17",
            "bracket": ["Round of 16", "Match 1"],
            "date": "2026-01-31",
            "matchup": { "team1": "confidence", "team2": "lhc" },
            "maps": [
                { "slug": "map1", "map": "nuke", "result": "13:9", "url": "https://www.challengermode.com/s/JBProLeague/games/2d619f8e-30d2-4858-3e5d-08de5760407d" },
                { "slug": "map2", "map": "mrg", "result": "10:13", "url": "https://www.challengermode.com/s/JBProLeague/games/7175a05f-eedb-42c4-3f85-08de5760407d" },
                { "slug": "map3", "map": "d2", "result": "13:16", "url": "https://www.challengermode.com/s/JBProLeague/games/c4c54fc4-2437-436d-40ca-08de5760407d" }
            ],
            "note": "ANa stood in for GooseBreeder."
        },
        {
            "slug": "match25",
            "bracket": ["Quarter finals", "Match 1"],
            "date": "2026-02-01",
            "matchup": { "team1": "lhc", "team2": "imodium" },
            "maps": [
                {
                    "slug": "map1",
                    "map": "mrg",
                    "result": "13:9",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/81ce05d4-8760-46c7-5178-08de60ebcb60",
                    "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "url": "https://www.twitch.tv/videos/2686043957", "name": "VOD", "duration": "00:27:18-01:30:49" }] }]
                },
                {
                    "slug": "map2",
                    "map": "anc",
                    "result": "6:13",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/06d931df-c556-416a-f0dc-08de6174dbff",
                    "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "url": "https://www.twitch.tv/videos/2686043957", "name": "VOD", "duration": "01:44:08-02:19:48" }] }]
                },
                {
                    "slug": "map3",
                    "map": "anb",
                    "result": "13:3",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/0cfe618d-21c1-4ab3-f16c-08de6174dbff",
                    "streams": [
                        {
                            "caster": "Affinity",
                            "language": "en",
                            "tags": ["official"],
                            "parts": [
                                { "url": "https://www.twitch.tv/videos/2686043957", "name": "Part 1", "duration": "02:30:53-02:52:13" },
                                { "url": "https://www.twitch.tv/videos/2686043957", "name": "Part 2", "duration": "03:12:38-03:39:29" }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "slug": "match29",
            "bracket": ["Semi finals", "Match 1"],
            "date": "2026-02-01",
            "matchup": { "team1": "lhc", "team2": "FUTURE W" },
            "maps": [
                {
                    "slug": "map1",
                    "map": "d2",
                    "result": "13:8",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/21e0df3f-0cab-4069-f26b-08de6174dbff",
                    "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "url": "https://www.twitch.tv/videos/2686043957", "name": "VOD", "duration": "03:54:08-04:38:11" }] }]
                },
                {
                    "slug": "map2",
                    "map": "anc",
                    "result": "13:1",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/4832d50d-3931-43e3-f2f2-08de6174dbff",
                    "streams": [{ "caster": "Affinity", "language": "en", "tags": ["official"], "parts": [{ "url": "https://www.twitch.tv/videos/2686043957", "name": "VOD", "duration": "04:47:28-05:12:30" }] }]
                }
            ]
        },
        {
            "slug": "match31",
            "bracket": ["Final", "Match 1"],
            "date": "2026-02-01",
            "matchup": { "team1": "lhc", "team2": "Fingers Crossed Fe" },
            "maps": [
                {
                    "slug": "map1",
                    "map": "anc",
                    "result": "4:13",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/cc437516-3c05-4895-f763-08de6174dbff",
                    "streams": [{ "caster": "Fabbelit0", "language": "en", "tags": ["official"], "parts": [{ "url": "https://www.twitch.tv/videos/2686313152", "name": "VOD", "duration": "00:46:12-01:20:02" }] }]
                },
                {
                    "slug": "map2",
                    "map": "mrg",
                    "result": "6:13",
                    "url": "https://www.challengermode.com/s/JBProLeague/games/1d0dd259-cfec-4957-f872-08de6174dbff",
                    "streams": [{ "caster": "Fabbelit0", "language": "en", "tags": ["official"], "parts": [{ "url": "https://www.twitch.tv/videos/2686313152", "name": "VOD", "duration": "01:24:17-02:02:11" }] }]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/src/lib/data/events/2026-01-17-jbpl-2026-fe-1-q1.json
{
    "$schema": "../schemas/event.schema.json",

    "slug": "jbpl-2026-fe-1-q1",
    "name": "JB Pro League 2026 Female #1 Qualifier 1",
    "duration": { "start": "2026-01-17", "end": "2026-01-18" },
    "urls": {
        "Officail Website": "https://jbproleague.com/news/11b110d1-1125-483a-b5bd-bcbd115afac4",
        "Bracket": "https://www.challengermode.com/s/JBProLeague/tournaments/2433d911-686d-46d3-7ad9-08de3ae2e258"
    },
    "participants": { "big": "big-equipa-2026-1", "pkb": "peekaboo-2026-1", "lhc": "let-her-cook-2026-1" },
    "matches": [
        {
            "slug": "m17",
            "bracket": ["Round of 16", "Match 1"],
            "date": "2026-01-17",
            "matchup": { "team1": "big", "team2": "chicken friday" },
            "maps": [
                { "slug": "map1", "map": "mrg", "result": "13:11", "url": "https://www.challengermode.com/s/JBProLeague/games/f9c84d20-cf58-4409-4eaf-08de50e4e82f", "streams": [{ "url": "https://www.twitch.tv/videos/2672352294", "caster": "Affinity", "language": "en", "duration": "00:22:26-01:12:32" }] },
                { "slug": "map2", "map": "anc", "result": "13:9", "url": "https://www.challengermode.com/s/JBProLeague/games/45499927-1f28-43e9-4f58-08de50e4e82f", "streams": [{ "url": "https://www.twitch.tv/videos/2672352294", "caster": "Affinity", "language": "en", "duration": "01:25:11-02:04:33" }] }
            ]
        },
        {
            "slug": "m23",
            "bracket": ["Round of 16", "Match 7"],
            "date": "2026-01-17",
            "matchup": { "team1": "lhc", "team2": "DONT WORRY" },
            "maps": [
                { "slug": "map1", "map": "mrg", "result": "13:11", "url": "https://www.challengermode.com/s/JBProLeague/games/d9b053bf-4778-4cbf-4ef4-08de50e4e82f" },
                { "slug": "map2", "map": "ovp", "result": "8:13", "url": "https://www.challengermode.com/s/JBProLeague/games/a1a45b5e-b61f-406c-4f8c-08de50e4e82f", "streams": [{ "url": "https://www.twitch.tv/videos/2672352294", "caster": "Affinity", "language": "en", "duration": "02:08:05-02:08:10", "tags": ["incomplete"] }] },
                { "slug": "map3", "map": "anc", "result": "13:9", "url": "https://www.challengermode.com/s/JBProLeague/games/156b5721-df54-4fc7-502b-08de50e4e82f", "streams": [{ "url": "https://www.twitch.tv/videos/2672352294", "caster": "Affinity", "language": "en", "duration": "02:29:26-03:01:16" }] }
            ]
        },
        {
            "slug": "m24",
            "bracket": ["Round of 16", "Match 8"],
            "date": "2026-01-17",
            "matchup": { "team1": "pkb", "team2": "LUNAR FE" },
            "maps": [
                { "slug": "map1", "map": "d2", "result": "16:12", "url": "https://www.challengermode.com/s/JBProLeague/games/5a508d64-c21c-4961-4fd5-08de50e4e82f" },
                { "slug": "map2", "map": "nuke", "result": "7:13", "url": "https://www.challengermode.com/s/JBProLeague/games/d1e60e0d-a11d-469d-50b3-08de50e4e82f", "streams": [{ "url": "https://www.twitch.tv/videos/2672352294", "caster": "Affinity", "language": "en", "duration": "03:02:52-03:26:32", "tags": ["incomplete"] }] },
                { "slug": "map3", "map": "anc", "result": "16:13", "url": "https://www.challengermode.com/s/JBProLeague/games/c9b970db-ae4f-4638-5164-08de50e4e82f", "streams": [{ "url": "https://www.twitch.tv/videos/2672352294", "caster": "Affinity", "language": "en", "duration": "03:46:52-04:32:28" }] }
            ]
        },
        {
            "slug": "m25",
            "bracket": ["Quarter finals", "Match 1"],
            "date": "2026-01-18",
            "matchup": { "team1": "big", "team2": "IDA NexGen" },
            "maps": [
                { "slug": "map1", "map": "anb", "result": "13:4", "url": "https://www.challengermode.com/s/JBProLeague/games/a7a35592-b767-4bb0-1af1-08de5669da63" },
                { "slug": "map2", "map": "mrg", "result": "13:8", "url": "https://www.challengermode.com/s/JBProLeague/games/29729e3e-c979-4ef3-1b4e-08de5669da63" }
            ]
        },
        {
            "slug": "m28",
            "bracket": ["Quarter finals", "Match 4"],
            "date": "2026-01-18",
            "matchup": { "team1": "lhc", "team2": "pkb" },
            "maps": [
                { "slug": "map1", "map": "mrg", "result": "13:4", "url": "https://www.challengermode.com/s/JBProLeague/games/d3ecde69-91a9-48e1-1af6-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Affinity", "language": "en", "duration": "00:33:35-00:59:59", "tags": ["official"] }] },
                { "slug": "map2", "map": "anc", "result": "11:13", "url": "https://www.challengermode.com/s/JBProLeague/games/6ddc02df-3a4b-4279-1b4b-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Affinity", "language": "en", "duration": "01:15:14-01:51:27", "tags": ["official"] }] },
                { "slug": "map3", "map": "d2", "result": "11:13", "url": "https://www.challengermode.com/s/JBProLeague/games/39176e60-4a9b-41cf-1bca-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Affinity", "language": "en", "duration": "02:04:02-02:44:55", "tags": ["official"] }] }
            ]
        },
        {
            "slug": "m29",
            "bracket": ["Semi finals", "Match 1"],
            "date": "2026-01-18",
            "matchup": { "team1": "big", "team2": "Fingers Crossed Fe" },
            "maps": [
                { "slug": "map1", "map": "d2", "result": "13:3", "url": "https://www.challengermode.com/s/JBProLeague/games/ab08bc9e-faa4-4a2b-1cb5-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Affinity", "language": "en", "duration": "03:28:36-03:59:23", "tags": ["official"] }] },
                { "slug": "map2", "map": "mrg", "result": "16:13", "url": "https://www.challengermode.com/s/JBProLeague/games/0575363b-3800-4e1a-1ef1-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Affinity", "language": "en", "duration": "04:13:09-05:09:58", "tags": ["official"] }] }
            ]
        },
        {
            "slug": "m30",
            "bracket": ["Semi finals", "Match 2"],
            "date": "2026-01-18",
            "matchup": { "team1": "Pigeons", "team2": "pkb" },
            "maps": [
                { "slug": "map1", "map": "anc", "result": "16:14", "url": "https://www.challengermode.com/s/JBProLeague/games/7da54e7c-f15c-41f4-20be-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Sxstem", "language": "en", "duration": "06:20:52-07:21:37", "tags": ["official"] }] },
                { "slug": "map2", "map": "mrg", "result": "13:11", "url": "https://www.challengermode.com/s/JBProLeague/games/ad1c0aad-f30d-4217-2171-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Sxstem", "language": "en", "duration": "07:31:43-08:19:43", "tags": ["official"] }] }
            ]
        },
        {
            "slug": "m31",
            "bracket": ["Final", "Match 1"],
            "date": "2026-01-18",
            "matchup": { "team1": "big", "team2": "Pigeons" },
            "maps": [
                { "slug": "map1", "map": "d2", "result": "2:13", "url": "https://www.challengermode.com/s/JBProLeague/games/dccb7b58-b8a9-4258-2320-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Sxstem", "language": "en", "duration": "08:51:40-09:19:03", "tags": ["official"] }] },
                { "slug": "map2", "map": "mrg", "result": "13:8", "url": "https://www.challengermode.com/s/JBProLeague/games/9e626949-f099-4c38-23bd-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Sxstem", "language": "en", "duration": "09:29:13-10:17:02", "tags": ["official"] }] },
                { "slug": "map3", "map": "anc", "result": "9:13", "url": "https://www.challengermode.com/s/JBProLeague/games/9ccd16a4-2577-4486-2500-08de5669da63", "streams": [{ "url": "https://www.twitch.tv/videos/2673270257", "caster": "Sxstem", "language": "en", "duration": "10:26:57-11:05:30", "tags": ["official"] }] }
            ]
        }
    ]
}
