=== isonovio/ninjas-archive/data/schemas/official-event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "brackets"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "official-match.schema.json#/$defs/tag" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "note": { "type": "string" }
    }
}

=== isonovio/ninjas-archive/data/twins/events/2023-01-28--esl-impact-cashcup-eu-2023-winter-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-winter-2",
    "name": "ESL Impact Cash Cup: Europe - Winter 2023 #2",
    "duration": { "start": "2023-01-28", "end": "2023-01-29" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Winter/2" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2188" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2188" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-01-28",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "ASTRONUTS" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17024858" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-01-28",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "MostValuablePlayers" } },
                    "maps": [
                        { "id": 1, "map": "vtg", "result": "16:4", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17024925" }] },
                        { "id": 2, "map": "ovp", "result": "16:11", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17024941" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-01-29",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Angels" } },
                    "maps": [
                        { "id": 1, "map": "mrg", "result": "16:11", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17025109" }] },
                        { "id": 2, "map": "ovp", "result": "16:10", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17025150" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2022-10-25--girlgamer-esports-festival-2022.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "girlgamer-esports-festival-2022",
    "name": "GIRLGAMER Esports Festival 2022",
    "duration": { "start": "2022-10-25", "end": "2023-03-18" },
    "links": [{ "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/GIRLGAMER_Esports_Festival/2022" }],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2" } }],
    "brackets": [
        {
            "slug": "s1",
            "brackets": [
                {
                    "slug": "d1",
                    "name": "Ceuta",
                    "links": [{ "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/GIRLGAMER_Esports_Festival/2022/Ceuta" }],
                    "brackets": [
                        {
                            "slug": "s1--qualifiers",
                            "brackets": [
                                {
                                    "slug": "q1",
                                    "name": "Open Qualifier #1",
                                    "links": [
                                        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/GIRLGAMER_Esports_Festival/2022/Ceuta/Qualifier/1" },
                                        { "name": "ESEA", "url": "https://play.esea.net/events/2048" },
                                        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2048" }
                                    ],
                                    "brackets": [
                                        {
                                            "slug": "r2",
                                            "name": "R2",
                                            "matches": [
                                                {
                                                    "id": 3,
                                                    "date": "2022-10-25",
                                                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Flawless" } },
                                                    "maps": [
                                                        { "id": 1, "map": "ovp", "result": "10:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16990413" }] }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "slug": "q2",
                                    "name": "Open Qualifier #2",
                                    "links": [
                                        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/GIRLGAMER_Esports_Festival/2022/Ceuta/Qualifier/2" },
                                        { "name": "ESEA", "url": "https://play.esea.net/events/2049" },
                                        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2049" }
                                    ],
                                    "brackets": [
                                        {
                                            "slug": "r2",
                                            "name": "R2",
                                            "matches": [
                                                {
                                                    "id": 5,
                                                    "date": "2022-10-27",
                                                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "GirlGamers" } },
                                                    "maps": [
                                                        { "id": 1, "map": "ovp", "result": "16:8", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16991665" }] }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "slug": "r3",
                                            "name": "R3",
                                            "matches": [
                                                {
                                                    "id": 3,
                                                    "date": "2022-10-27",
                                                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Clown5" } },
                                                    "maps": [
                                                        { "id": 1, "map": "ovp", "result": "16:13", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16991701" }] }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "slug": "r4",
                                            "name": "R4",
                                            "matches": [
                                                {
                                                    "id": 2,
                                                    "date": "2022-10-28",
                                                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Flawless" } },
                                                    "maps": [
                                                        { "id": 1, "map": "ovp", "result": "16:1", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16992139" }] },
                                                        { "id": 2, "map": "vtg", "result": "12:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16992144" }] },
                                                        { "id": 3, "map": "d2", "result": "16:11", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16992150" }] }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "slug": "r5",
                                            "name": "R5",
                                            "matches": [
                                                {
                                                    "id": 1,
                                                    "date": "2022-10-28",
                                                    "lineups": { "team1": { "name": "NOFEAR5" }, "team2": { "shorthand": "cfs" } },
                                                    "maps": [
                                                        { "id": 1, "map": "vtg", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16992166" }] }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "slug": "s2--finals",
                            "tags": ["lan"],
                            "matches": [
                                {
                                    "id": 1,
                                    "name": "Opening Match 1",
                                    "date": "2022-11-17",
                                    "lineups": { "team1": { "name": "NAVI Javelins" }, "team2": { "shorthand": "cfs" } },
                                    "maps": [{ "id": 1, "map": "d2", "result": "16:11" }]
                                },
                                {
                                    "id": 4,
                                    "name": "Lower Final",
                                    "date": "2022-11-17",
                                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "9Pandas Fearless" } },
                                    "maps": [
                                        { "id": 1, "map": "ovp", "result": "14:16" },
                                        { "id": 2, "map": "d2", "result": "4:16" }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2024-05-25--esl-impact-cashcup-eu-2024-10.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2024-10",
    "name": "ESL Impact Cash Cup 2024: Europe #10",
    "duration": { "start": "2024-05-25", "end": "2024-05-26" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/2024/Europe/10" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/451803dd-6708-43f8-8a5d-64786fda9ece" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "team": "nipi", "players": ["nayomy", "qiyarah", "ramziin", "spike", "vilga"] } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 1,
                    "date": "2024-05-25",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Fifth Venom" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-34d5bb33-a6c6-4e30-a824-d519dae4d1cf" }],
                    "maps": [{ "id": 1, "map": "mrg", "result": "13:0" }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Round of 8",
            "matches": [
                {
                    "id": 1,
                    "date": "2024-05-26",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "5bites" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-4e04625c-a96e-41cd-bc9d-c36563d07538" }],
                    "maps": [{ "id": 1, "map": "anc", "result": "13:4" }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Semi-finals",
            "matches": [
                {
                    "id": 1,
                    "date": "2024-05-26",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "ex-FORZE Ladies" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-333fd9db-ef87-4d69-969a-2ea4f16cf48b" }],
                    "maps": [
                        { "id": 1, "map": "anb", "result": "10:13" },
                        { "id": 2, "map": "anc", "result": "16:14" },
                        { "id": 3, "map": "mrg", "result": "13:9" }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "matches": [
                {
                    "id": 1,
                    "name": "Grand Final",
                    "date": "2024-05-26",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Crescent" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-ecdea9a2-2b2d-4f2c-ab71-e2e5de1f0209" }],
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "7:13" },
                        { "id": 2, "map": "anb", "result": "9:13" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2023-04-08--esl-impact-cashcup-eu-2023-spring-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-spring-1",
    "name": "ESL Impact Cash Cup: Europe - Spring 2023 #1",
    "duration": { "start": "2023-04-08", "end": "2023-04-09" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Spring/1" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2412" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2412" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-04-08",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Pasiba Esports" } },
                    "maps": [{ "id": 1, "map": "vtg", "result": "16:7", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17047289" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-04-08",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "YeYO" } },
                    "maps": [
                        { "id": 1, "map": "anc", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17047298" }] },
                        { "id": 2, "map": "ovp", "result": "16:12", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17047318" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-04-09",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Mixxxen" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "16:13", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17047426" }] },
                        { "id": 2, "map": "ovp", "result": "19:15", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17047429" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2024-04-27--elite-fe-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "elite-fe-1",
    "name": "ELITE FE #1",
    "duration": { "start": "2024-04-27", "end": "2024-04-27" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ELITE_FE/1" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/036cc9e9-5651-4945-9791-26004d59df71" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7772/european-pro-league-female-season-1" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-1" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 5,
                    "date": "2024-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "AKA HERO Althea" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-bf036a06-bf9d-4b49-8464-f3395ad7c8cb" }],
                    "maps": [{ "id": 1, "map": "anc", "result": "13:3" }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Quarterfinals",
            "matches": [
                {
                    "id": 3,
                    "date": "2024-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Permitta W" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-2a057bc7-00ca-46f3-bccd-f1e6c2658a8e" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2371247/navi-javelins-vs-nip-impact-european-pro-league-female-season-1" }
                    ],
                    "maps": [{ "id": 1, "map": "anc", "result": "13:11" }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semifinals",
            "matches": [
                {
                    "id": 2,
                    "date": "2024-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "ENCE Athena" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-5c4384f4-084d-4c59-8471-4e534447ef66" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2371852/nip-impact-vs-ence-athena-elite-fe-cup-1" }
                    ],
                    "maps": [{ "id": 1, "map": "anb", "result": "13:11" }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Grand Final",
            "matches": [
                {
                    "id": 1,
                    "date": "2024-04-27",
                    "lineups": { "team1": { "name": "Pigeons" }, "team2": { "shorthand": "nipi" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-938b4aad-4417-4a7f-b55a-39167b3a41b0" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2371853/nip-impact-vs-pigeons-elite-fe-cup-1" }
                    ],
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "13:2" },
                        { "id": 2, "map": "anc", "result": "13:6" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2023-05-06--esl-impact-cashcup-eu-2023-spring-3.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-spring-3",
    "name": "ESL Impact Cash Cup: Europe - Spring 2023 #3",
    "duration": { "start": "2023-05-06", "end": "2023-05-07" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Spring/3" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2432" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2432" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7187/esl-impact-spring-2023-cash-cup-3-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-05-06",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "cute" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:5", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17058602" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-05-06",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "YeYO" } },
                    "maps": [
                        { "id": 1, "map": "mrg", "result": "16:8", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17058618" }] },
                        { "id": 2, "map": "ovp", "result": "16:6", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17058633" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-05-07",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Astralis W" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2364223/nip-impact-vs-astralis-w-esl-impact-spring-2023-cash-cup-3-europe" }],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "16:6", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17058767" }] },
                        { "id": 2, "map": "inf", "result": "16:10", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17058772" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2025-04-27--elite-fe-3.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "elite-fe-3",
    "name": "ELITE FE #3",
    "duration": { "start": "2025-04-27", "end": "2025-04-27" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ELITE_FE/3" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/3bc894cd-b091-4bb9-97e1-9c2396d427d3" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Opening Round",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Apranik" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-5550b6d3-7a42-4127-bb3c-46def18792ad" }],
                    "maps": [],
                    "note": "Apranik forfeited the match."
                }
            ]
        },
        {
            "slug": "r2b1",
            "name": "Upper Quarterfinals",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Spray and slay" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-077c8edb-d10d-4ce9-ad05-599bb3614c52" }],
                    "maps": [{ "id": 1, "map": "inf", "result": "13:8" }]
                }
            ]
        },
        {
            "slug": "r3b1",
            "name": "Upper Semifinals",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "noHYP3" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-404938d6-ec38-4c72-97a2-1f48867f2150" }],
                    "maps": [{ "id": 1, "map": "mrg", "result": "13:9" }]
                }
            ]
        },
        {
            "slug": "r4b1",
            "name": "Upper Final",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Prototype Blaze" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-efb5f3f8-bb1c-4570-886a-5ce19f936e7c" }],
                    "maps": [{ "id": 1, "map": "d2", "result": "13:10" }]
                }
            ]
        },
        {
            "slug": "r5",
            "name": "Grand Final",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-04-27",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Prototype Blaze" } },
                    "maps": [
                        {
                            "id": 1,
                            "map": "anc",
                            "result": "13:11",
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-0de33fa5-ac0b-4058-8500-2d4ed11ed8fe/scoreboard" }]
                        },
                        {
                            "id": 2,
                            "map": "trn",
                            "result": "13:4",
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/match/room/1-efeebb9f-5f93-4b52-8b3c-3005b534e559" }]
                        }
                    ]
                }
            ]
        }
    ]
}
