=== isonovio/ninjas-archive/data/schemas/official-event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "brackets"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "official-match.schema.json#/$defs/tag" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "note": { "type": "string" }
    }
}

=== isonovio/ninjas-archive/data/twins/events/2024-04-06--tradeit-league-fe-masters-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "tradeit-league-fe-masters-2",
    "name": "Tradeit League FE Masters #2",
    "duration": { "start": "2024-04-06", "end": "2024-04-07" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/Tradeit_League/FE_Masters/2" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/d74fc0f8-f6be-430a-aa21-3a74a05c1ef1" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-1" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 8,
                    "date": "2024-04-06",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Nemesis" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-cb446570-63d6-4db4-a2a7-38472396a6d0" }],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "13:7" },
                        { "id": 2, "map": "mrg", "result": "13:3" }
                    ]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Round of 8",
            "matches": [
                {
                    "id": 4,
                    "date": "2024-04-06",
                    "lineups": { "team1": { "name": "GUILD" }, "team2": { "shorthand": "nipi" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-095b1e83-aee6-4f23-868b-7d52890f3f45" }],
                    "maps": [
                        { "id": 1, "map": "mrg", "result": "4:13" },
                        { "id": 2, "map": "anb", "result": "13:7" },
                        { "id": 3, "map": "anc", "result": "6:13" }
                    ]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semi-finals",
            "matches": [
                {
                    "id": 2,
                    "date": "2024-04-07",
                    "lineups": { "team1": { "name": "Fearless Cheetahs" }, "team2": { "shorthand": "nipi" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-3b863ef6-9a9e-41d7-b3a9-04edafec72d4" }],
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "5:13" },
                        { "id": 2, "map": "vtg", "result": "10:13" }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Grand final",
            "tags": ["transparent"],
            "matches": [
                {
                    "id": 1,
                    "date": "2024-04-07",
                    "lineups": { "team1": { "name": "Pigeons" }, "team2": { "shorthand": "nipi" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-7ef03d42-e212-43c3-bd99-acf200a2ec93" }],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "13:10" },
                        { "id": 2, "map": "vtg", "result": "13:9" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2022-12-03--esl-impact-cashcup-eu-2022-autumn-5.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-autumn-5",
    "name": "ESL Impact Cash Cup: Europe - Autumn 2022 #5",
    "duration": { "start": "2022-12-03", "end": "2022-12-04" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Autumn/5" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2084" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2084" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "R1",
            "matches": [
                {
                    "id": 3,
                    "date": "2022-12-03",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "VisAVis" } },
                    "maps": [{ "id": 1, "map": "anc", "result": "16:5", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17006482" }] }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 2,
                    "date": "2022-12-03",
                    "lineups": { "team1": { "name": "Clown5" }, "team2": { "shorthand": "cfs" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "4:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17006596" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-12-03",
                    "lineups": { "team1": { "name": "9Pandas Fearless" }, "team2": { "shorthand": "cfs" } },
                    "maps": [
                        { "id": 1, "map": "vtg", "result": "6:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17006617" }] },
                        { "id": 2, "map": "anc", "result": "3:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17006636" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-12-04",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "shinigami" } },
                    "maps": [
                        { "id": 1, "map": "ovp", "result": "16:12", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17006774" }] },
                        { "id": 2, "map": "anc", "result": "16:12", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17006794" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2021-02-07--ambush-fe-cup-2021-winter.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "ambush-fe-cup-2021-winter",
    "name": "Ambush Female Winter Cup",
    "duration": { "start": "2021-02-07", "end": "2021-02-28" },
    "links": [{ "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/Ambush_Female_Cup/2021/Winter" }],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-1" } }],
    "brackets": [
        {
            "slug": "p1--qualifiers",
            "brackets": [
                {
                    "slug": "q1",
                    "name": "Open Qualifier #1",
                    "duration": { "start": "2021-02-07", "end": "2021-02-07" },
                    "links": [{ "name": "Esportal", "url": "https://esportal.com/en/tournament/1121/ambush-female-winter-cup-1/info" }]
                },
                {
                    "slug": "q2",
                    "name": "Open Qualifier #2",
                    "duration": { "start": "2021-02-14", "end": "2021-02-14" },
                    "links": [{ "name": "Esportal", "url": "https://esportal.com/en/tournament/1122/ambush-female-winter-cup-2/info" }],
                    "brackets": [
                        {
                            "slug": "r2",
                            "name": "R2",
                            "matches": [
                                {
                                    "id": 3,
                                    "date": "2021-02-14",
                                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "777 Femme" } },
                                    "links": [{ "name": "Esportal", "url": "https://esportal.com/en/tournament/1122/ambush-female-winter-cup-2/match/2665788" }],
                                    "maps": [{ "id": 1, "map": "d2", "result": "16:12" }]
                                }
                            ]
                        },
                        {
                            "slug": "r3",
                            "name": "R3",
                            "matches": [
                                {
                                    "id": 2,
                                    "date": "2021-02-14",
                                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "TeamSaiprah" } },
                                    "links": [{ "name": "Esportal", "url": "https://esportal.com/en/tournament/1122/ambush-female-winter-cup-2/match/2666068" }],
                                    "maps": [{ "id": 1, "map": "inf", "result": "7:16" }]
                                }
                            ]
                        }
                    ]
                },
                {
                    "slug": "q3",
                    "name": "Open Qualifier #3",
                    "duration": { "start": "2021-02-20", "end": "2021-02-20" },
                    "links": [{ "name": "Esportal", "url": "https://esportal.com/en/tournament/1123/ambush-female-winter-cup-3/info" }],
                    "brackets": [
                        {
                            "slug": "r2",
                            "name": "R2",
                            "matches": [
                                {
                                    "id": 7,
                                    "date": "2021-02-20",
                                    "lineups": { "team1": { "name": "Fragbox Female" }, "team2": { "shorthand": "nsc" } },
                                    "links": [{ "name": "Esportal", "url": "https://esportal.com/en/tournament/1123/ambush-female-winter-cup-3/match/2689234" }],
                                    "maps": [{ "id": 1, "map": "inf", "result": "19:16" }]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2023-09-30--esl-impact-cashcup-eu-2023-autumn-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-autumn-1",
    "name": "ESL Impact Cash Cup: Europe - Autumn 2023 #1",
    "duration": { "start": "2023-09-30", "end": "2023-10-01" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Autumn/1" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/1afd9553-3f4c-4b1a-9aee-3f18d5758aca" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-09-30",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "PARTIZAN RED" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-ef0c2590-9844-48d2-b37e-351f5ab0e82c" }],
                    "maps": [{ "id": 1, "map": "ovp", "result": "13:6" }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semi-finals",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-09-30",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Washington5M" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-c484ea84-5766-4b52-b79a-dfd0fc36b087" }],
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "10:13" },
                        { "id": 2, "map": "ovp", "result": "10:13" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2025-02-23--elite-fe-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "elite-fe-2",
    "name": "ELITE FE #2",
    "duration": { "start": "2025-02-23", "end": "2025-02-23" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ELITE_FE/2" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/b9ae6415-8e84-4c0d-8845-782a582cbada" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 3,
                    "date": "2025-02-23",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Outsiders" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-c8360cfb-ba1f-4313-b9bc-60eb94206b87" }],
                    "maps": [{ "id": 1, "map": "anc", "result": "13:7" }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Quarterfinals",
            "matches": [
                {
                    "id": 2,
                    "date": "2025-02-23",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Needachance" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-1246dcb8-6029-45e5-8048-675d6b7750f5" }],
                    "maps": [{ "id": 1, "map": "d2", "result": "13:0" }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semifinals",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-02-23",
                    "lineups": { "team1": { "name": "also" }, "team2": { "shorthand": "nipi" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-024287d2-8f7e-4268-8634-d1deea8c48ef" }],
                    "maps": [{ "id": 1, "map": "anb", "result": "3:13" }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Grand Final",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-02-23",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Prototype Blaze" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-3164e4de-e08a-4547-92ae-84d354406302" }],
                    "maps": [
                        { "id": 1, "map": "trn", "result": "13:6" },
                        { "id": 2, "map": "anb", "result": "13:8" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2022-05-07--esl-impact-cashcup-eu-2022-spring-4.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-spring-4",
    "name": "ESL Impact Cash Cup: Europe - Spring 2022 #4",
    "duration": { "start": "2022-05-07", "end": "2022-05-08" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Spring/4" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1438" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1438" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6567/esl-impact-spring-2022-cash-cup-4-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 5,
                    "date": "2022-05-07",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "rising from the ashes" } },
                    "maps": [{ "id": 1, "map": "inf", "result": "16:13", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16909843" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 3,
                    "date": "2022-05-07",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "Entropiq Queens" } },
                    "maps": [{ "id": 1, "map": "inf", "result": "16:12", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16909904" }] }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-05-08",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "NAVI Javelins" } },
                    "maps": [
                        { "id": 1, "map": "d2", "result": "7:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16910354" }] },
                        { "id": 2, "map": "nuke", "result": "14:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16910376" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2023-04-22--esl-impact-cashcup-eu-2023-spring-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-spring-2",
    "name": "ESL Impact Cash Cup: Europe - Spring 2023 #2",
    "duration": { "start": "2023-04-22", "end": "2023-04-23" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Spring/2" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2422" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2422" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 4,
                    "date": "2023-04-22",
                    "lineups": { "team1": { "name": "Larance" }, "team2": { "shorthand": "nipi" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "5:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053593" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 2,
                    "date": "2023-04-22",
                    "lineups": { "team1": { "team": "cfs" }, "team2": { "shorthand": "nipi" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "4:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053635" }] },
                        { "id": 2, "map": "ovp", "result": "11:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053661" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-04-23",
                    "lineups": { "team1": { "name": "NAVI Javelins" }, "team2": { "shorthand": "nipi" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "1:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053774" }] },
                        { "id": 2, "map": "anc", "result": "16:10", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053780" }] },
                        { "id": 3, "map": "mrg", "result": "16:9", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053787" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2023-02-04--esl-impact-cashcup-eu-2023-winter-3.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-winter-3",
    "name": "ESL Impact Cash Cup: Europe - Winter 2023 #3",
    "duration": { "start": "2023-02-04", "end": "2023-02-05" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Winter/3" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2189" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2189" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7045/esl-impact-winter-2023-cash-cup-3-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-02-04",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Queend" } },
                    "maps": [{ "id": 1, "map": "mrg", "result": "16:7", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028250" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-02-04",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "TFW" } },
                    "maps": [
                        { "id": 1, "map": "ovp", "result": "16:3", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028282" }] },
                        { "id": 2, "map": "mrg", "result": "19:17", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028297" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-02-05",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Capybara Gay" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2361674/nip-impact-vs-capybara-esl-impact-winter-2023-cash-cup-3-europe" }],
                    "maps": [
                        { "id": 1, "map": "inf", "result": "16:11", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028424" }] },
                        { "id": 2, "map": "vtg", "result": "16:9", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028461" }] }
                    ]
                }
            ]
        }
    ]
}
