=== isonovio/ninjas-archive/data/schemas/official-event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "brackets"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "official-match.schema.json#/$defs/tag" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "note": { "type": "string" }
    }
}

=== isonovio/ninjas-archive/data/twins/events/2023-08-12--esl-impact-cashcup-eu-2023-summer-4.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-summer-4",
    "name": "ESL Impact Cash Cup: Europe - Summer 2023 #4",
    "duration": { "start": "2023-08-12", "end": "2023-08-12" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Summer/4" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/c497b599-4203-4bfc-b65b-af8b2d29073e" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7351/esl-impact-summer-2023-cash-cup-4-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 3,
                    "date": "2023-08-12",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Let Her Cook" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-30f7d9ad-dcf0-442d-b733-cc3b921be91a" }],
                    "maps": [{ "id": 1, "map": "anc", "result": "11:16" }]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2022-12-14--esl-impact-2023-katowice.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-2023-katowice",
    "name": "ESL Impact Katowice 2023",
    "duration": { "start": "2022-12-14", "end": "2023-02-12" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact/2023/Katowice" },
        { "name": "ESL", "url": "https://pro.eslgaming.com/csgo/impact/katowice/" },
        { "name": "Rules", "url": "https://drive.google.com/drive/folders/1T6wVEKOXslH_j3B_By_L69pF2s2eqJWd" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2" } }],
    "brackets": [
        {
            "slug": "s1",
            "name": "Qualifiers",
            "tags": ["transparent"],
            "brackets": [
                {
                    "slug": "d1eu",
                    "name": "Europe",
                    "brackets": [
                        {
                            "slug": "q1",
                            "name": "Qualifier #1",
                            "links": [
                                { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact/2023/Katowice/Europe/1" },
                                { "name": "ESEA", "url": "https://play.esea.net/events/2096" },
                                { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2096" },
                                { "name": "HLTV", "url": "https://www.hltv.org/events/6946/esl-impact-katowice-2023-europe-open-qualifier-1" }
                            ],
                            "brackets": [
                                {
                                    "slug": "r1",
                                    "name": "R1",
                                    "matches": [
                                        {
                                            "id": 9,
                                            "date": "2022-12-14",
                                            "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "XI Fe Gamerpay" } },
                                            "maps": [{ "id": 1, "map": "anc", "result": "16:5", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17010648" }] }]
                                        }
                                    ]
                                },
                                {
                                    "slug": "r2",
                                    "name": "R2",
                                    "matches": [
                                        {
                                            "id": 6,
                                            "date": "2022-12-14",
                                            "lineups": { "team1": { "name": "FIFTY FIVE POWER" }, "team2": { "shorthand": "cfs" } },
                                            "maps": [{ "id": 1, "map": "ovp", "result": "19:22", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17010683" }] }]
                                        }
                                    ]
                                },
                                {
                                    "slug": "r3",
                                    "name": "R3",
                                    "matches": [
                                        {
                                            "id": 3,
                                            "date": "2022-12-14",
                                            "lineups": { "team1": { "name": "Astralis W" }, "team2": { "shorthand": "cfs" } },
                                            "maps": [{ "id": 1, "map": "ovp", "result": "16:6", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17010716" }] }]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "slug": "q2",
                            "name": "Qualifier #2",
                            "links": [
                                { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact/2023/Katowice/Europe/2" },
                                { "name": "ESEA", "url": "https://play.esea.net/events/2160" },
                                { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2160" },
                                { "name": "HLTV", "url": "https://www.hltv.org/events/6950/esl-impact-katowice-2023-europe-open-qualifier-2" }
                            ],
                            "brackets": [
                                {
                                    "slug": "r2",
                                    "name": "R2",
                                    "matches": [
                                        {
                                            "id": 4,
                                            "date": "2022-12-17",
                                            "lineups": { "team1": { "name": "ASTRONUTS" }, "team2": { "shorthand": "cfs" } },
                                            "maps": [{ "id": 1, "map": "anc", "result": "14:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17011418" }] }]
                                        }
                                    ]
                                },
                                {
                                    "slug": "r3",
                                    "name": "R3",
                                    "matches": [
                                        {
                                            "id": 2,
                                            "date": "2022-12-17",
                                            "lineups": { "team1": { "team": "nipi" }, "team2": { "shorthand": "cfs" } },
                                            "maps": [{ "id": 1, "map": "ovp", "result": "19:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17011428" }] }]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2023-03-25--esl-impact-cashcup-eu-2023-winter-6.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-winter-6",
    "name": "ESL Impact Cash Cup: Europe - Winter 2023 #6",
    "duration": { "start": "2023-03-25", "end": "2023-03-26" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Winter/6" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2192" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2192" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "R1",
            "matches": [
                {
                    "id": 8,
                    "date": "2023-03-25",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "5ye70log1" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:1", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043170" }] }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 4,
                    "date": "2023-03-25",
                    "lineups": { "team1": { "name": "YeYO" }, "team2": { "shorthand": "nipi" } },
                    "maps": [{ "id": 1, "map": "anb", "result": "12:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043202" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 2,
                    "date": "2023-03-25",
                    "lineups": { "team1": { "name": "Astralis W" }, "team2": { "shorthand": "nipi" } },
                    "maps": [
                        { "id": 1, "map": "anc", "result": "6:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043224" }] },
                        { "id": 2, "map": "mrg", "result": "15:19", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043239" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-03-26",
                    "lineups": { "team1": { "name": "9 Pandas Fearless" }, "team2": { "shorthand": "nipi" } },
                    "maps": [
                        { "id": 1, "map": "vtg", "result": "16:10", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043338" }] },
                        { "id": 2, "map": "mrg", "result": "14:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043350" }] },
                        { "id": 3, "map": "anb", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17043356" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2022-06-25--esl-impact-cashcup-eu-2022-summer-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-summer-1",
    "name": "ESL Impact Cash Cup: Europe - Summer 2022 #1",
    "duration": { "start": "2022-06-25", "end": "2022-06-26" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Summer/1" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1624" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1624" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6635/esl-impact-summer-2022-cash-cup-1-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "R1",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-25",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "Pandaric Winx" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:4", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937246" }] }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-25",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "FIFTYFIVEPOWER" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:4", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937268" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-25",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "MostValuablePlayers" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937300" }] },
                        { "id": 2, "map": "ovp", "result": "10:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937326" }] },
                        { "id": 3, "map": "d2", "result": "8:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937348" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2024-05-18--tradeit-league-fe-masters-3.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "tradeit-league-fe-masters-3",
    "name": "Tradeit League FE Masters #3",
    "duration": { "start": "2024-05-18", "end": "2024-05-19" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/Tradeit_League/FE_Masters/3" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/3c610442-0b27-43d9-8e06-4a57c01beaae" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 3,
                    "date": "2024-05-18",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Let Her Cook" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-0c82cbd9-6f6b-41e3-a313-775aa3036178" }],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "5:13" },
                        { "id": 2, "map": "vtg", "result": "13:8" },
                        { "id": 3, "map": "anb", "result": "13:11" }
                    ]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Round of 8",
            "matches": [
                {
                    "id": 2,
                    "date": "2024-05-18",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "ex-GUILD" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-184d0167-75ac-4f2c-9956-f21490e5119e" }],
                    "maps": [
                        { "id": 1, "map": "mrg", "result": "13:16" },
                        { "id": 2, "map": "inf", "result": "13:5" },
                        { "id": 3, "map": "anb", "result": "13:10" }
                    ]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semi-finals",
            "matches": [
                {
                    "id": 1,
                    "date": "2024-05-19",
                    "lineups": { "team1": { "name": "Pigeons" }, "team2": { "shorthand": "nipi" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-05619703-15b1-45e6-8169-e668e9f81d1d" }],
                    "maps": [
                        { "id": 1, "map": "inf", "result": "13:9" },
                        { "id": 2, "map": "d2", "result": "13:9" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2021-05-29--ambush-fe-cup-2021-spring.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "ambush-fe-cup-2021-spring",
    "name": "Ambush Female Spring Cup",
    "duration": { "start": "2021-05-29", "end": "2021-05-29" },
    "links": [{ "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/Ambush_Female_Cup/2021/Spring" }],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-1" } }],
    "brackets": [
        {
            "slug": "s2",
            "links": [{ "name": "Challengermode", "url": "https://www.challengermode.com/s/ACL/tournaments/ec16f8d0-d7c0-41dd-eafc-08d91eab5d22" }],
            "brackets": [
                {
                    "slug": "s1--group-stage",
                    "brackets": [
                        {
                            "slug": "g4",
                            "name": "Group D",
                            "matches": [
                                {
                                    "id": 2,
                                    "date": "2021-05-29",
                                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "Bifrost Blue" } },
                                    "maps": [
                                        {
                                            "id": 1,
                                            "map": "d2",
                                            "result": "9:16",
                                            "links": [{ "name": "Challengermode", "url": "https://www.challengermode.com/s/ACL/games/fe322754-f66b-4f69-7e77-08d91c58a461" }]
                                        }
                                    ]
                                },
                                {
                                    "id": 3,
                                    "date": "2021-05-29",
                                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "Arcane Wave" } },
                                    "maps": [
                                        {
                                            "id": 1,
                                            "map": "trn",
                                            "result": "5:16",
                                            "links": [{ "name": "Challengermode", "url": "https://www.challengermode.com/s/ACL/games/98b6c6c0-28f6-47ac-7d23-08d91c58a461" }]
                                        }
                                    ]
                                },
                                {
                                    "id": 6,
                                    "date": "2021-05-29",
                                    "lineups": { "team1": { "name": "Hyperspace girls" }, "team2": { "shorthand": "nsc" } },
                                    "maps": [
                                        {
                                            "id": 1,
                                            "map": "nuke",
                                            "result": "16:4",
                                            "links": [{ "name": "Challengermode", "url": "https://www.challengermode.com/s/ACL/games/61cedb11-443c-4949-7fc1-08d91c58a461" }]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/ninjas-archive/data/twins/events/2022-08-24--esl-impact-league-s2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-league-s2",
    "name": "ESL Impact League Season 2",
    "duration": { "start": "2022-08-24", "end": "2022-11-27" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_League/Season_2" },
        { "name": "ESL", "url": "https://pro.eslgaming.com/csgo/impact/season2/" },
        { "name": "Rules", "url": "https://drive.google.com/drive/folders/1T6wVEKOXslH_j3B_By_L69pF2s2eqJWd" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2" } }],
    "brackets": [
        {
            "slug": "s1",
            "brackets": [
                {
                    "slug": "d1eu",
                    "name": "Europe",
                    "links": [{ "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_League/Season_2/Europe" }],
                    "brackets": [
                        {
                            "slug": "s1--qualifiers",
                            "brackets": [
                                {
                                    "slug": "q1",
                                    "name": "Open Qualifier #1",
                                    "links": [
                                        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_League/Season_2/Europe/Qualifier/1" },
                                        { "name": "ESEA", "url": "https://play.esea.net/events/1790" },
                                        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1790" }
                                    ],
                                    "brackets": [
                                        {
                                            "slug": "r2",
                                            "name": "R2",
                                            "matches": [
                                                {
                                                    "id": 8,
                                                    "date": "2022-08-24",
                                                    "lineups": { "team1": { "name": "Venary Female" }, "team2": { "shorthand": "cfs" } },
                                                    "maps": [
                                                        { "id": 1, "map": "ovp", "result": "1:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16965210" }] }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "slug": "r3",
                                            "name": "R3",
                                            "matches": [
                                                {
                                                    "id": 4,
                                                    "date": "2022-08-24",
                                                    "lineups": { "team1": { "name": "Clown5" }, "team2": { "shorthand": "cfs" } },
                                                    "maps": [
                                                        { "id": 1, "map": "nuke", "result": "10:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16965477" }] }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "slug": "r4",
                                            "name": "R4",
                                            "matches": [
                                                {
                                                    "id": 2,
                                                    "date": "2022-08-25",
                                                    "lineups": { "team1": { "name": "SUL CLAN" }, "team2": { "shorthand": "cfs" } },
                                                    "maps": [
                                                        { "id": 1, "map": "mrg", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16965962" }] },
                                                        { "id": 2, "map": "vtg", "result": "12:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16966156" }] },
                                                        { "id": 3, "map": "ovp", "result": "16:8", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16966171" }] }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "slug": "q2",
                                    "name": "Open Qualifier #2",
                                    "links": [
                                        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_League/Season_2/Europe/Qualifier/2" },
                                        { "name": "ESEA", "url": "https://play.esea.net/events/1791" },
                                        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1791" }
                                    ],
                                    "brackets": [
                                        {
                                            "slug": "r2",
                                            "name": "R2",
                                            "matches": [
                                                {
                                                    "id": 8,
                                                    "date": "2022-08-27",
                                                    "lineups": { "team1": { "name": "HIPER JELONKI" }, "team2": { "shorthand": "cfs" } },
                                                    "maps": [],
                                                    "note": "CPH Flames Shieldmaidens forfeited the match."
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
