=== isonovio/ninjas-archive/data/schemas/player.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "nickname", "nationality"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "nickname": { "type": "string" },
        "name": { "type": "string" },
        "birthday": { "type": "string", "format": "date" },
        "nationality": { "$ref": "nationality.schema.json" },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["twin", "ninja"]
        }
    }
}

=== isonovio/ninjas-archive/data/twins/players/missy.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "missy",
    "nickname": "Missy",
    "name": "Halat Naby",
    "birthday": "1992-11-08",
    "nationality": "nl",
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/FreeNN-" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/9984/missy" },
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/Missy" },
        { "name": "Steam", "url": "https://steamcommunity.com/profiles/76561198025363723" },
        { "name": "Twitter", "url": "https://x.com/MissyRezero" }
    ]
}

=== isonovio/ninjas-archive/data/twins/players/maneschijnx.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "maneschijnx",
    "nickname": "ManeschijnX",
    "name": "Luna Akkermans",
    "birthday": "2000-09-06",
    "nationality": "nl",
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/2760749" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/De13th" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/22603/maneschijnx" },
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ManeschijnX" },
        { "name": "Steam", "url": "https://steamcommunity.com/profiles/76561199008948232" },
        { "name": "Twitch", "url": "https://www.twitch.tv/maneschijnx" },
        { "name": "Twitter", "url": "https://x.com/a_luna_mila" },
        { "name": "YouTube", "url": "https://www.youtube.com/@ManeschijnXcs" }
    ]
}

=== isonovio/ninjas-archive/data/twins/players/kezziwow.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "kezziwow",
    "nickname": "kezziwOw",
    "name": "Héjja Kászandrá",
    "birthday": "1996-01-04",
    "nationality": "hu",
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/781496" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/kezziwOw" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/13550/kezziwow" },
        { "name": "Instagram", "url": "https://www.instagram.com/kezziwow" },
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/KezziwOw" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/krumplibogarka/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/kezziwow" },
        { "name": "Twitter", "url": "https://x.com/kezziwow" }
    ]
}

=== isonovio/ninjas-archive/data/twins/players/gina.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "gina",
    "nickname": "Gina",
    "name": "Melania Mylioti",
    "birthday": "1991-09-17",
    "nationality": "nl",
    "links": [
        { "name": "Profile", "url": "https://www.melania.gg/" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/1510/gina" },
        { "name": "Twitter", "url": "https://x.com/MelaniaMylioti" }
    ]
}
